name: context variables demo
#on: push
on: workflow_dispatch
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context varibales
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "This repository name is ${{ github.repository }}"
      - name: Print all variables under github
        run: echo "${{ toJSON(github) }}"

      - name: Print environment varibales
        run: |
          printenv
          echo "$GITHUB_SHA"