name: or condition demo
#on: push
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Chnadra or chandra reddy
        if: github.actor == 'chandra' || github.actor == 'chandrareddytiyyagura'
        run: echo "It is triggered by either Chandra or chandrareddytiyyagura"
