name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "A demo build"
          echo "Build completed"
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Testing
          run: |
            echo "Testing started"
            echo "Testing completed"
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deployment
          run: |
            echo "Deployment started"
            echo "Deployment ended"