name: ENV Demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_demo:
    env:
      APP_ENV: "Dev1"
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to ENV
        env:
          APP_ENV: "DEV-Step"
        run: echo "App is connecting to $APP_ENV"
