name: outpts demo
on: push

jobs:
  build:
    outputs:
      version: ${{ steps.build_step.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        id: build_step
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        id: deploy_step
        run: echo "We are deploying the app with version ${{ needs.build.outputs.version }}"